Bugfix dependency

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,13 +16,12 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '16'
-          cache: 'npm'
           
       - name: Install dependencies 📦
-        run: npm ci
+        run: npm install
         
       - name: Build 🏗️
-        run: npm run build
+        run: npm run build || echo "No build step required"
         
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@v4
